# Generated by Django 4.2.7 on 2023-11-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0004_alter_moto_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preço'),
        ),
    ]
