# Generated by Django 4.2.7 on 2023-11-23 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0006_alter_moto_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='ano',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
