# Generated by Django 4.2.7 on 2023-11-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0007_alter_moto_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='preco',
            field=models.IntegerField(),
        ),
    ]
