# Generated by Django 4.2.7 on 2023-11-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0010_moto_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='preco',
            field=models.CharField(max_length=11),
        ),
    ]
