# Generated by Django 4.2.5 on 2023-09-29 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_reserva_stand"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reserva",
        ),
        migrations.DeleteModel(
            name="Stand",
        ),
    ]
