# Generated by Django 4.2.5 on 2023-09-29 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stands", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnpj", models.CharField(max_length=11)),
                ("nome_empresa", models.CharField(max_length=150)),
                ("categoria_empresa", models.CharField(max_length=150)),
                ("quitado", models.BooleanField(default=False)),
                (
                    "stand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stands.stand"
                    ),
                ),
            ],
        ),
    ]
